######################## default configuration ####################
baseURL = "/"
title = "wasmCloud Documentation"
theme = "godocs-1"
# google analytics
googleAnalytics = "UA-190314505-2" # example : UA-123-45
# disable language
disableLanguages = ["fr"] # desable language from here

# hugo outputs
[outputs]
home = [ "HTML", "JSON"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"
page = "/"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
attributes = ""
page = "/"

[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
attributes = ""
page = "/"

[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"
attributes = ""
page = "/"


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/turbolinks/turbolinks.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/match-height/jquery.matchHeight-min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/search.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
attributes = ""
page = "search/"

[[params.plugins.js]]
link = "plugins/search/mark.js"
attributes = ""
page = "search/"

[[params.plugins.js]]
link = "plugins/search/search-page.js"
attributes = ""
page = "search/"


############## English navigation ###############

# main menu
[[Languages.en.menu.main]]
name = "Home"
url = "https://wasmcloud.com"
weight = 1

[[Languages.en.menu.main]]
name = "Docs Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Github"
url = "https://github.com/wasmcloud"
weight = 2

# footer menu
[[Languages.en.menu.footer]]
name = "Installation"
url = "overview/installation/"
weight = 1

[[Languages.en.menu.footer]]
name = "Contact"
url = "contact"
weight = 2

[[Languages.en.menu.footer]]
name = "Github"
url = "https://github.com/wasmcloud/"
weight = 3



#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "wasmCloud is a secure, distributed WebAssembly actor runtime"
author = "wasmCloud LLC"
# contact form action
contact_form_action = "https://formspree.io/f/mvovydey" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[[params.nav_button]]
style = "outline" # available style: solid, outline
label = "releases"
link = "releases"

[[params.nav_button]]
style = "solid" # available style: solid, outline
label = "contact"
link = "contact"

  
############################# social site ########################
#[[params.social]]
#title = "facebook"
#icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
#link = "https://www.facebook.com/wasmcloud-102542298375661/"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/wasmcloud"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/wasmcloud"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "https://www.linkedin.com/company/wasmcloud"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
# copyright
copyright = "2022 &copy wasmCloud Project Authors. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our Trademark Usage page: [https://www.linuxfoundation.org/trademark-usage](https://www.linuxfoundation.org/trademark-usage)"

# banner
[Languages.en.banner]
title = "wasmCloud"
subtitle = "wasmCloud is a distributed platform for writing portable business logic that can run anywhere from the edge to the cloud. Secure by default, wasmCloud aims to strip wasteful boilerplate from the developer experience and return _joy_ to the act of building distributed applications."
image = "images/banner.png"

# call to action
[Languages.en.call_to_action]
enable = true
title = "Still have questions?"
image = "images/cta-illustration.jpg"
content = "Whether you just want to chat, have specific questions, or are ready to contribute to wasmcloud, our open community is always looking to grow!"

  # call to action button
  [Languages.en.call_to_action.button]
  enable = "true"
  label = "Join the Community"
  link = "contact"


